accounts/urls.py
from django.urls import path
from accounts import views


app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path("login/", views.login, name="login"),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
]

app/urls.py
from django.urls import path
from app import views

urlpatterns = [
    path("echo/", views.echo_page),
    path("liveblog/", views.liveblog_index, name="home"),
    path("liveblog/posts/<int:post_id>/", views.post_partial, name="post_partial"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('', include('app.urls')),
    path('', RedirectView.as_view(pattern_name="chat:index"), name="root"),
]

config/templates/base.html
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>django channels</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block extra-style %}{% endblock %}
</head>
<body>
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
                장고 채널스
            </a>

            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 link-secondary">채팅</a></li>
            </ul>

            <div class="col-md-3 text-end">
                {% if not user.is_authenticated %}
                    <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary me-2">로그인</a>
                    <a href="{% url 'accounts:signup' %}" class="btn btn-primary">회원가입</a>
                {% else %}
                    <a href="{% url 'accounts:profile' %}" class="btn btn-outline-primary me-2">프로필</a>
                    <a href="{% url 'accounts:logout' %}" class="btn btn-primary">로그아웃</a>
                {% endif %}
            </div>
        </header>

        {% bootstrap_messages %}

        {% block content %}

        {% endblock content %}
    </div>
    {% block extra-script %}{% endblock %}
</body>
</html>